# Generated by Django 5.2.5 on 2025-08-17 20:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RentalProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('brand', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('price_per_day', models.DecimalField(decimal_places=2, default=15000.0, max_digits=10)),
                ('lumens', models.IntegerField()),
                ('resolution', models.CharField(max_length=50)),
                ('hdmi', models.BooleanField(default=True)),
                ('vga', models.BooleanField(default=False)),
                ('total_quantity', models.PositiveIntegerField(default=0)),
                ('image', models.ImageField(blank=True, null=True, upload_to='rentals/')),
                ('description', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RentalAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('available_quantity', models.PositiveIntegerField()),
                ('rental_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='rentals.rentalproduct')),
            ],
            options={
                'unique_together': {('rental_product', 'date')},
            },
        ),
    ]
