# Generated by Django 5.2.5 on 2025-08-17 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rentalavailability',
            options={'verbose_name': 'Rental Availability', 'verbose_name_plural': 'Rental Availabilities'},
        ),
        migrations.AlterModelOptions(
            name='rentalproduct',
            options={'verbose_name': 'Rental Product', 'verbose_name_plural': 'Rental Products'},
        ),
    ]
