# Generated by Django 5.2.5 on 2025-10-13 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='condition',
            field=models.CharField(choices=[('brand_new', 'Brand New'), ('tokunbo', 'Tokunbo (Used)')], default='brand_new', help_text='Specify whether the projector is brand new or tokunbo (used).', max_length=20),
        ),
    ]
